### ISSUE TITLE
No precommit configuration

### ISSUE THREAD

**Issue by winny-** [winny-/sillypaste#10]
It should run black and pep8 checker.  Maybe check yamls or jsons too.

**Comment by BodaleDenis** [comment]
I would like to help with this

**Comment by winny-** [comment]
Sure thing!  Looking forward to reviewing your PR.  :)

**Comment by BodaleDenis** [comment]
Ok, so please assign it to me 😄

**Comment by winny-** [comment]
Done =)

**Comment by BodaleDenis** [comment]
Nice, PR is active so you can review :D

**Comment by winny-** [comment]
#12 has been merged 🎊  :shipit:
